apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: joaquin02-aks-helm-release
  namespace: default
spec:
  chart:
    spec:
      chart: ./capi/charts/aks
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 10m
  values:
    name: joaquin02-aks
    clusterResourceGroup: joaquin-cluster-02
    controlAgentPoolName: claspooljoaquinCluster02
    workerAgentPoolName: wraspooljoaquinCluster02
