apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: joaquin01-aks-helm-release
  namespace: default
spec:
  chart:
    spec:
      chart: ./capi/charts/aks
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m
  values:
    name: westus2-joaquin01-aks
    clusterResourceGroup: capi-demo-clusters
    controlAgentPoolName: claspooljoaquin
    workerAgentPoolName: wraspooljoaquin
    location: westus2
    virtualNetwork:
      name: joaquin01-vnet
